- name: Entry point
  hosts: windows
  display_skipped_hosts: false
  vars_files: [environment.yml]

  tasks:
    - name: Environment setup
      block:
        - name: Remove startup delay for WinRM service
          ansible.builtin.include_tasks: tasks/environment/winrm_delay.yml

        - name: Language setup
          ansible.builtin.include_tasks: tasks/environment/language.yml
          vars:
            user: "{{ username }}"
            admin: "{{ admin_username }}"

        - name: User setup
          ansible.builtin.include_tasks: tasks/environment/users.yml
          vars:
            user: "{{ username }}"
            admin: "{{ admin_username }}"

        - name: Restrictions setup
          ansible.builtin.include_tasks: tasks/environment/restrictions.yml
          vars:
            user: "{{ username }}"

        - name: Wifi setup
          ansible.builtin.include_tasks: tasks/environment/wifi.yml
          vars:
            wifi_ssid: "{{ wifi.ssid }}"
            wifi_password: "{{ wifi.password }}"

    - name: Reboot
      ansible.builtin.include_tasks: tasks/utils/reboot.yml

    - name: Package setup
      block:
        - name: Create directory
          ansible.builtin.include_tasks: tasks/packages/directory.yml
          vars:
            path: "{{ local_path }}"

        - name: Download packages
          ansible.builtin.include_tasks: tasks/packages/download.yml
          vars:
            url: "{{ ftp.url }}"
            user: "{{ ftp.user }}"
            password: "{{ ftp.password }}"
            path: "{{ local_path }}"
            packages: "{{ pkgs | dict2items }}"

        - name: Install win_package packages
          ansible.builtin.include_tasks: tasks/packages/win_package.yml
          vars:
            path: "{{ local_path }}"
            packages: "{{ pkgs | dict2items }}"

        - name: Install win_powershell packages
          ansible.builtin.include_tasks: tasks/packages/win_powershell.yml
          vars:
            path: "{{ local_path }}"
            packages: "{{ pkgs | dict2items }}"

        - name: Install win_chocolatey packages
          ansible.builtin.include_tasks: tasks/packages/win_chocolatey.yml
          vars:
            packages: "{{ pkgs | dict2items }}"

    - name: Final reboot
      ansible.builtin.include_tasks: tasks/utils/reboot.yml
