#* This is default values for Russian language support

- name: Set the region format to Russian
  community.windows.win_region:
    format: ru-RU
    location: 203
    unicode_language: ru-RU
    copy_settings: true
