#* Remove delay on automatic startup for winrm service

- name: Remove WinRM delay
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\WinRM
    name: DelayedAutoStart
    data: 0
    type: dword
    state: present
