#* Installing package offline with win_powershell module
#! Specify the 'path' variable (outside w/ 'var.path' key or directly inside the task)
#! Specify the 'packages' variable (outside w/ 'var.packages' key or directly inside the task)

- name: Unzip packages
  ansible.windows.win_shell: "Expand-Archive -Path {{ item.value.file }} -DestinationPath {{ path }}"
  args:
    chdir: "{{ path }}"
  loop: "{{ packages }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.value.checked
    - item.value.type == 'win_powershell'

#* Scripts in environment.yml looks like: .\Install.ps1 -Arg1 Value
- name: Install packages
  ansible.windows.win_shell: "{{ item.value.script }}"
  args:
    chdir: "{{ path }}/{{ item.key }}"
  loop: "{{ packages }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.value.checked
    - item.value.type == 'win_powershell'
