#* Installing package online with chocolatey
#! Specify the 'packages' variable (outside w/ 'var.packages' key or directly inside the task)

- name: Install packages
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.key }}"
    state: present
  loop: "{{ packages }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.value.checked
    - item.value.type == 'win_chocolatey'
