#* Installing package offline with win_powershell module
#! Specify the 'path' variable (outside w/ 'var.path' key or directly inside the task)
#! Specify the 'packages' variable (outside w/ 'var.packages' key or directly inside the task)

- name: Unzip packages
  ansible.windows.win_powershell:
    chdir: "{{ path }}"
    script: |
      [CmdletBinding()]
      param (
        [String]$Path,
        [String]$DestinationPath
      )

      Expand-Archive -Path $Path -DestinationPath $DestinationPath
    parameters:
      Path: "{{ item.value.file }}"
      DestinationPath: "{{ path }}"
  loop: "{{ packages }}"
  when:
    - item.value.checked
    - item.value.type == 'win_powershell'
- name: Install packages
  ansible.windows.win_shell: "{{ item.value.script }}"
  args:
    chdir: "{{ path }}/{{ item.key }}"
  loop: "{{ packages }}"
  when:
    - item.value.checked
    - item.value.type == 'win_powershell'
