#* Installing package offline with win_powershell module
#! Specify the 'path' variable (outside w/ 'var.path' key or directly inside the task)
#! Specify the 'packages' variable (outside w/ 'var.packages' key or directly inside the task)

- name: Unzip packages
  ansible.windows.win_powershell:
    chdir: "{{ path }}"
    script: |
      [CmdletBinding()]
      param (
        [String]$Path,
        [String]$DestinationPath
      )

      Expand-Archive -Path $Path -DestinationPath $DestinationPath
    parameters:
      Path: "{{ item.value.file }}"
      DestinationPath: "{{ path }}"
  loop: "{{ packages }}"
  when:
    - item.checked
    - item.type == 'win_powershell'

- name: Install packages
  ansible.windows.win_powershell:
    chdir: "{{ path }}/{{ item.key }}"
    script: |
      [CmdletBinding()]
      param (
        [String]$File,
        [String]$Arguments
      )

      Powershell.exe -ExecutionPolicy Bypass -File $File $Arguments
    parameters:
      File: "{{ item.value.script }}"
      Arguments: "{{ item.value.arguments }}"
  loop: "{{ packages }}"
  when:
    - item.value.checked
    - item.value.type == 'win_powershell'
