#* Installing package offline with win_package module
#! Specify the 'path' variable (outside w/ 'var.path' key or directly inside the task)
#! Specify the 'packages' variable (outside w/ 'var.packages' key or directly inside the task)

- name: Install packages
  ansible.windows.win_package:
    path: "{{ path }}/{{ item.value.file }}"
    arguments: "{{ item.value.arguments }}"
    state: present
  loop: "{{ packages }}"
  when:
    - item.value.checked
    - item.value.type == 'win_package'
